"""This module defines sound objects created either by a bat or by other sounds as an echo"""

import math
import uuid

from supporting_files.utilities import call_directionality_factor

# TODO: EchoSound is inherited from DirectSound
# need info on what it echoes off of


class EchoSound:
    def __init__(
        self,
        parameters_df,
        origin,
        creation_time,
        emitter_id,
        initial_spl,
        reflected_from,
        direction_vector,
    ):
        self.parameters_df = parameters_df
        self.origin = origin
        self.creation_time = creation_time
        self.emitter_id = emitter_id
        self.initial_spl = initial_spl
        self.current_spl = initial_spl
        self.current_radius = 0.0

        self.speed = self.parameters_df["SOUND_SPEED"]
        # Keep track of when to kill sound; either when db is below 20 or when out of arena
        self.active = True
        self.reflected_obstacles = (
            set()
        )  # Keep track on number of echoes generated by self
        self.reflected_from = reflected_from
        self.id = uuid.uuid4()
        self.direction_vector = direction_vector

        self.arena_width = self.parameters_df["ARENA_WIDTH"]
        self.arena_length = self.parameters_df["ARENA_LENGTH"]
        self.call_directionality = self.parameters_df["CALL_DIRECTIONALITY"]

    def update(self, current_time):
        """Function to propagate sound with time.
        This function updates the radius of the sound disk with time.
        Also, ensures sounds outside the arena are "disabled" and no longer tracked.

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
        """
        elapsed = current_time - self.creation_time
        self.current_radius = self.speed * elapsed

        # Calculate spl with distance and air absorption

        if self.current_radius > 0:
            distance_effect = 20 * math.log10(self.current_radius / 1)
            self.current_spl = (
                self.initial_spl
                - distance_effect
                - (self.parameters_df["AIR_ABSORPTION"] * self.current_radius)
            )

        if self.check_if_sound_outside_arena():
            self.active = False

    def contains_point(self, point):
        """Checks whether a given point is within the sound disk.
        This function helps to decide when to generate echoes from objects.

        Args:
            point (Vector): _description_

        Returns:
            _type_: _description_
        """
        distance = self.origin.distance_to(point)
        return distance <= self.current_radius and distance >= max(
            0,
            self.current_radius
            - self.parameters_df["CALL_DURATION"] * self.parameters_df["SOUND_SPEED"],
        )

    def sound_directionality(self, angle_between_sound_and_receiver):
        sound_directionality = call_directionality_factor(
            a=self.call_directionality,
            theta=angle_between_sound_and_receiver,
        )
        return sound_directionality

    def spl_at_receiver(self, receiver_position):
        angle_between_sound_and_receiver = self.direction_vector.angle_between(
            receiver_position
        )
        sound_directionality = self.sound_directionality(
            angle_between_sound_and_receiver
        )

        distance_between_sound_and_receiver = receiver_position.distance_to(self.origin)

        if distance_between_sound_and_receiver == 0:
            spl_corrected_for_width = self.initial_spl
        else:
            distance_effect = 20 * math.log10(distance_between_sound_and_receiver / 1)
            spl_corrected_for_width = (
                self.initial_spl
                - distance_effect
                - (
                    self.parameters_df["AIR_ABSORPTION"]
                    * distance_between_sound_and_receiver
                )
            )
        return spl_corrected_for_width + sound_directionality

    def check_if_sound_outside_arena(self):
        """Checks if sound is outside the bounds of the arena.
        Sound obejct is no longer tracked if its outside the arena.

        Returns:
            Bool: True if sound is outside the bounds of the arena, else False.
        """
        if (self.current_radius) > max(self.arena_length, self.arena_width):
            return True
        else:
            return False

    def __repr__(self):
        return (
            f"EchoSound(origin={self.origin}, radius={self.current_radius:.2f}, "
            f"spl={self.current_spl:.1f}dB,"
            f"emitter={self.emitter_id}, creation_time={self.creation_time})"
        )


class DirectSound(EchoSound):
    def __init__(
        self, parameters_df, origin, creation_time, emitter_id, direction_vector
    ):
        # self.parameters_df= parameters_df
        super().__init__(
            parameters_df=parameters_df,
            origin=origin,
            creation_time=creation_time,
            emitter_id=emitter_id,
            initial_spl=parameters_df["EMITTED_SPL"],
            reflected_from=None,
            direction_vector=direction_vector,
        )

        self.current_spl = self.initial_spl
        self.current_radius = 0
        # Keep track of sound disc width

        self.active = True
        # Direct sounds can only reflect once/ i.e. per collision only one echo ngl
        self.reflected_obstacles = (
            set()
        )  # Track obstacles that it reflected off of in order to cap this in the future
        self.wall_id = None

    def create_echo(self, point, current_time, normal, reflected_from):
        """Handles EchoSound creation by the sound object.
        Creates an echo at the specified point.

        Args:
            point (Vector): point of reflection of sound
            current_time (float): time, in seconds, for which the simualtion has been running.
            normal (Vector): Normal vector from the object that the sound reflects from.
            reflected_from (string): The id of the object the sound reflects from.

        Returns:
            EchoSound: The generated EchoSound object.
        """
        # print(self.direction_vector)
        angle_between_sound_and_reflection_point = self.direction_vector.angle_between(
            point
        )
        call_directionality = call_directionality_factor(
            a=self.parameters_df["CALL_DIRECTIONALITY"],
            theta=angle_between_sound_and_reflection_point,
        )

        object_type = reflected_from[0:4]
        if object_type == "wall":
            reflection_loss = self.parameters_df["REFLECTION_LOSS_WALL"]
        else:
            reflection_loss = self.parameters_df["REFLECTION_LOSS"]
        # print(point, self.origin, self.wall_id, reflected_from)
        distance_between_sound_and_echo = self.origin.distance_to(point)
        # print(distance_between_sound_and_echo)
        distance_effect_for_echoes = 20 * math.log10(
            distance_between_sound_and_echo / 1
        )
        spl_corrected_for_width = (
            self.initial_spl
            - distance_effect_for_echoes
            - (self.parameters_df["AIR_ABSORPTION"] * distance_between_sound_and_echo)
        )

        reflected_spl = spl_corrected_for_width - reflection_loss + call_directionality
        if reflected_spl < self.parameters_df["HEARING_THRESHOLD"]:
            return None

        echo = EchoSound(
            parameters_df=self.parameters_df,
            origin=point,
            creation_time=current_time,
            emitter_id=self.emitter_id,
            initial_spl=reflected_spl,
            reflected_from=reflected_from,
            direction_vector=normal,
        )
        echo.reflected_obstacles.update(self.reflected_obstacles)
        if object_type == "wall":
            # wall echoes are omnidirectional!
            echo.call_directionality = 0

        return echo

    def __repr__(self):
        return (
            f"DirectSound(origin={self.origin}, direction={self.direction_vector}, radius={self.current_radius:.2f}, "
            f"spl={self.current_spl:.1f}dB, emitter={self.emitter_id}), creation_time={self.creation_time}"
        )
