"""This module contains the code that describes a Bat object and its behaviours"""

import random

import numpy as np
from agents.class_sounds import DirectSound
from supporting_files.bats_response_to_sound import (
    decide_next_direction_based_on_consistency,
    decide_next_direction_based_on_loudest_sound,
)
from supporting_files.snr_implementation import (
    given_sound_objects_return_detected_sounds,
)
from supporting_files.supporting_functions_for_consistency import (
    given_parameters_df_return_grid_matrix_zeros,
)
from supporting_files.utilities import call_directionality_factor, make_dir, str2bool
from supporting_files.vectors import Vector


class Bat:
    _id_counter = 0

    def __init__(self, parameters_df, output_dir):
        self.id = Bat._id_counter
        Bat._id_counter += 1

        self.parameters_df = parameters_df.copy()  # .copy() is important!!!
        self.output_dir = output_dir

        self.position = Vector(
            random.uniform(1, self.parameters_df["ARENA_WIDTH"] - 1),
            random.uniform(1, self.parameters_df["ARENA_LENGTH"] - 1),
        )  # randomize initial position placement. you can also reset this in simulation.

        self.direction = Vector().random_direction()  # randomize start direction
        # allocentric axis is set to start direction
        self.allocentric_axis_y = self.direction

        time_step_size = self.parameters_df["TIME_STEP"]
        # find the number of decimal places to set rounding equal to time step size
        self.rounding_based_on_time_step = len(str(time_step_size).split(".")[1])

        self.call_rate = self.parameters_df["CALL_RATE"]
        self.time_since_last_call = np.round(
            random.uniform(0, 1 / self.call_rate),
            self.rounding_based_on_time_step,
        )

        # only stores DirectSound objects that was generated by it
        self.emitted_sounds = []
        self.emit_times = [-np.inf]

        self.speed = self.parameters_df["BAT_FAST_SPEED"]  # initial speed
        self.radius = self.parameters_df["BAT_RADIUS"]  # bat radius

        self.detections_for_directon_change = []  # initiate detection list
        self.time_since_directon_change = -np.inf  # time counter, direction change
        self.next_direction = self.direction  #

        self.memory_window_to_store_grids = []

        self.response_type = None
        self.cell_index_to_respond_to = [np.nan, np.nan]

        self.ipi_matrix = given_parameters_df_return_grid_matrix_zeros(
            self.parameters_df
        )[0]
        self.memory_window_sum_matrix = self.ipi_matrix.copy()

        self.ipi_matrix_timeseries = []

        self.any_consistent_sound = "no"
        self.is_bat_reflective_to_sound = str2bool("yes")

        self.list_to_store_sounds = []

    def update(self, current_time, sound_objects, temporal_masking_file):
        """Function to update bats with time.
        This function handles movement update of bat each time step.
        Also takes care of sound emission, detection of active sounds by the bats.
        Bat detections over time is also cleared and stored locally.

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
            sound_objects (EchoSound): direct and echo sounds that are currently active.
        """

        self.update_movement()
        self.emit_sounds(current_time, sound_objects)
        if self.id == 0 and self.time_since_directon_change == 0:
            print(f"bat_0_emit_at_{self.emit_times[-1]}")
        self.update_directon(current_time, sound_objects, temporal_masking_file)

        # just make sure egocentric is truly egocentric everywhere.
        reference_frame = self.parameters_df["SPATIAL_REFERENCE_FRAME"]
        if reference_frame == "egocentric":
            self.allocentric_axis_y = self.direction

    def update_movement(self):
        """Update poisition of Bat when called.
        Every timestep the position of the bat needs to be
        updated based on velcoity and direction.
        """
        # move bat every step
        if self.speed != 0:
            self.position += (
                self.direction * self.speed * self.parameters_df["TIME_STEP"]
            )
        elif self.speed < 0:
            raise ValueError("Negative speed, impossible!")

        # boundary checks with bounce

        if self.position.x <= 0 or self.position.x >= self.parameters_df["ARENA_WIDTH"]:
            self.direction.x *= -1
            self.next_direction = self.direction
        if (
            self.position.y <= 0
            or self.position.y >= self.parameters_df["ARENA_LENGTH"]
        ):
            self.direction.y *= -1
            self.next_direction = self.direction

    def emit_sounds(self, current_time, sound_objects):
        """Trigger sound emission by Bat.
        Whenever the function is called, it checks if sufficient time
        has passed and a DirectSoundObject is created.

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
            sound_objects (list): List containing all active sounds in the simulation
        """
        # time counter since last call
        self.time_since_last_call += self.parameters_df["TIME_STEP"]
        call_interval = 1.0 / self.call_rate

        # check if sufficient time has passed since last call.
        if self.time_since_last_call >= call_interval:
            sound = DirectSound(
                parameters_df=self.parameters_df,
                origin=self.position,
                creation_time=current_time,
                emitter_id=self.id,
                direction_vector=self.direction,
            )
            self.emitted_sounds.append(sound)
            self.emit_times.append(current_time)
            # if self.id != 0:
            sound_objects.append(sound)

            # make the bat stop executing its previous movement
            self.next_direction = self.direction

            # start the timer for direction change
            self.time_since_directon_change = 0
            # add jitter to the next call
            self.time_since_last_call = np.random.uniform(
                -self.parameters_df["NOISE_IN_CALL_RATE"],
                self.parameters_df["NOISE_IN_CALL_RATE"],
            )
            # reset detections that will be used for direction change
            self.detections_for_directon_change = []

    def convert_sound_to_dictionary(self, sound, current_time, received_spl):
        """converts a given sound to dictionary
        inorder to save only necessary information

        Args:
            sound (EchoSound): sound to convert
            current_time (float): simulation time
            received_spl (float): spl at the focal bat after sound directionaility
                        and spreading

        Returns:
            dictionary: dictionary version of the sound object
        """
        incident_direction = (sound.origin - self.position).normalize()
        sound_type = "direct" if isinstance(sound, DirectSound) else "echo"

        dictionary = {
            "time": current_time,
            "creation_time": sound.creation_time,
            "origin": (sound.origin.x, sound.origin.y),
            "distance_from_bat": sound.origin.distance_to(self.position),
            "received_spl": received_spl,
            "emitter_id": sound.emitter_id,
            "type": sound_type,
            "reflection_count": getattr(sound, "reflection_count", 0),
            "reflected_from": sound.reflected_from,
            "sound_object_id": sound.id,
            "sound_direction": (
                sound.direction_vector.x,
                sound.direction_vector.y,
            ),
            "incident_direction": (
                incident_direction.x,
                incident_direction.y,
            ),
            "bat_direction": (self.direction.x, self.direction.y),
            "bat_position": (self.position.x, self.position.y),
            "bat_last_call_time": self.emit_times[-1],
            "theta": np.degrees(
                self.allocentric_axis_y.angle_between(incident_direction)
            ),
        }
        return dictionary

    def given_sound_objects_return_sounds_at_bat_position(
        self, current_time, sound_objects
    ):
        """given sounds generate list of sounds that a bat can hear

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
            sound_objects (list): List containing all active sounds in the simulation
            detect_self_call (Bool): If true, add self call to detected, else, skip self call.

        Returns:
            list: sound detections given time.
        """
        array_of_sound_detections = []
        # if bat is calling it shouldnt hear anything
        is_bat_calling = (
            current_time < self.emit_times[-1] + self.parameters_df["CALL_DURATION"]
        )
        if is_bat_calling:
            return array_of_sound_detections
        for sound in sound_objects:

            is_sound_active = sound.active

            is_sound_self_call = sound.emitter_id == self.id and isinstance(
                sound, DirectSound
            )

            is_sound_reflected_from_self = sound.reflected_from == f"bat_{self.id}"

            if (
                not is_sound_active
                or is_sound_self_call
                or is_sound_reflected_from_self
            ):
                continue

            # sound can only be detected if bat is inside the sound wave
            if sound.contains_point(self.position):
                received_spl = sound.spl_at_receiver(self.position)

                angle_between_sound_and_bat = sound.direction_vector.angle_between(
                    self.position
                )
                hearing_directionality = call_directionality_factor(
                    a=self.parameters_df["HEARING_DIRECTIONALITY"],
                    theta=angle_between_sound_and_bat,
                )

                received_spl += hearing_directionality
                is_sound_audible = (
                    received_spl > self.parameters_df["HEARING_THRESHOLD"]
                )

                if not is_sound_audible:
                    continue
                array_of_sound_detections.append(
                    self.convert_sound_to_dictionary(sound, current_time, received_spl)
                )
        return array_of_sound_detections

    def cleanup_sounds(self, current_time, heard_sounds):
        """Stores the detections into a .npy file.
        After a fixed amount of time the detection list is stored
        into local memory and this is cleared from RAM.

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
        """
        # Keep only recent detections
        # clean up activates after every some steps to clear memory from RAM and store it on drive
        store_hearing = str2bool(self.parameters_df["STORE_HEARING"])

        if store_hearing and self.output_dir is not None:
            dir_to_store = self.output_dir + "/" + str(self.id)
            make_dir(dir_to_store)
            current_time_str = f"{current_time:.4f}".zfill(9)
            np.save(
                dir_to_store
                + f"/bat_{self.id}_received_sounds_snapshot_at_time_{current_time_str}.npy",
                heard_sounds,
            )
            np.save(
                dir_to_store
                + f"/bat_{self.id}_emitted_sounds_snapshot_at_time_{current_time_str}.npy",
                self.emitted_sounds,
            )
        self.emitted_sounds = []
        self.ipi_matrix_timeseries = []

    # inelligent movement
    def generate_random_direction(self):
        """assign a random direction to the bat"""
        direction = self.direction
        if random.random() < self.parameters_df["PROPENSITY_TO_CHANGE_DIRECTION"]:
            direction = Vector().random_direction()
        return direction

    def generate_direction_vector_given_sound(self, sound):
        """generate direction vector of any sound

        Args:
            sound (EchoSound): sound to convert to vector

        Returns:
            Vector: Vector form of the input sound
        """
        spl_of_sound = sound["received_spl"]

        normalized_sound_vector = (
            Vector(x=sound["origin"][0], y=sound["origin"][1]) - self.position
        ).normalize()

        vector_w_spl_magnitude = normalized_sound_vector * spl_of_sound
        return vector_w_spl_magnitude

    def decide_next_direction(self, detected_sound_objects):
        """decide next direction of bat based on sound"""
        behaviour_rule_to_use = self.parameters_df["BEHAVIOUR_RULE"]

        if behaviour_rule_to_use == "consistency":
            next_direction, response_type = decide_next_direction_based_on_consistency(
                self, detected_sound_objects
            )
        elif behaviour_rule_to_use == "loudest_sound":
            next_direction, response_type = (
                decide_next_direction_based_on_loudest_sound(
                    self, detected_sound_objects
                )
            )
        else:
            raise ValueError("unsupported behaviour rule")
        return next_direction.normalize(), response_type

    def update_directon(self, current_time, sound_objects, temporal_masking_file):
        """rotate bat according to fix angular speed

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
            sound_objects (list): list containing detected sounds
        """
        self.time_since_directon_change += self.parameters_df["TIME_STEP"]

        implement_snr = str2bool(self.parameters_df["IMPLEMENT_SNR"])
        min_sound_detection_fraction = self.parameters_df[
            "MINIMUM_SOUND_DETECTION_FRACTION"
        ]
        include_direct_sounds_in_response = str2bool(
            self.parameters_df["INCLUDE_DIRECT_SOUNDS_IN_RESPONSE"]
        )

        hearing_angle_threshold = np.radians(
            self.parameters_df["HEARING_ANGLE_THRESHOLD"]
        )

        direction_change_time_interval = self.parameters_df[
            "TIME_DELAY_FOR_DIRECTION_CHANGE"
        ]
        self.detections_for_directon_change.extend(
            self.given_sound_objects_return_sounds_at_bat_position(
                current_time, sound_objects
            )
        )
        # print(self.detections_for_directon_change)
        if (
            self.time_since_directon_change >= direction_change_time_interval
            and len(self.detections_for_directon_change) != 0
        ):

            if implement_snr:
                heard_sounds = given_sound_objects_return_detected_sounds(
                    self.detections_for_directon_change,
                    direction_change_time_interval,
                    hearing_angle_threshold,
                    temporal_masking_file,
                    min_sound_detection_fraction,
                    self.id,
                    include_direct_sounds_in_response,
                    self.parameters_df["CALL_DURATION"],
                    self.parameters_df["TIME_STEP"],
                    self.rounding_based_on_time_step,
                )
            else:
                heard_sounds = self.detections_for_directon_change

            # self.cleanup_sounds(current_time, heard_sounds)

            self.list_to_store_sounds.extend(heard_sounds)

            self.modulate_speed_call_rate()

            self.next_direction, self.response_type = self.decide_next_direction(
                heard_sounds
            )
            self.detections_for_directon_change = []
            self.time_since_directon_change = -np.inf

            if self.response_type == "attraction":
                self.speed = self.parameters_df["BAT_FAST_SPEED"]
        elif (
            self.time_since_directon_change >= direction_change_time_interval
            and len(self.detections_for_directon_change) == 0
        ):
            self.ipi_matrix = given_parameters_df_return_grid_matrix_zeros(
                self.parameters_df
            )[0]
            self.memory_window_sum_matrix = self.ipi_matrix.copy()

        rotation_speed = np.radians(self.parameters_df["BAT_ROTATION_SPEED"])
        rotation_speed_scaled_by_time_step = (
            rotation_speed * self.parameters_df["TIME_STEP"]
        )
        self.rotate_towards_given_degree(
            self.next_direction, rotation_speed_scaled_by_time_step
        )

    def rotate_towards_given_degree(self, new_direction, rotation_rate):
        """slowly rotate towards the new_direction from current_direction

        Args:
            new_direction (Vector): direction that the bat wants to end up in
            rotation_rate (Vector)): radians rotated per time step
        """

        current_direction = self.direction
        if current_direction != new_direction:
            angle_between_current_and_new = current_direction.angle_between(
                new_direction
            )

            if angle_between_current_and_new > rotation_rate:
                rotation_angle = 1 * rotation_rate
            elif angle_between_current_and_new < -rotation_rate:
                rotation_angle = -1 * rotation_rate
            else:
                rotation_angle = angle_between_current_and_new

            rotated_vector = current_direction.rotate(rotation_angle)
            self.direction = rotated_vector.normalize()

    def modulate_speed_call_rate(self):
        """Change call rate and speed if conditions are met."""
        if self.any_consistent_sound == "no":
            self.speed = self.parameters_df["BAT_FAST_SPEED"]
            self.call_rate = self.parameters_df["CALL_RATE_FAST"]
        else:
            self.speed = self.parameters_df["BAT_SPEED"]
            self.call_rate = self.parameters_df["CALL_RATE"]

    def __repr__(self):
        return f"Bat(id={self.id}, position={self.position})"
